export const environment = {
  production: false,
  name: 'Softlabit QA',
  domain: 'qa.softlabit.com',
  apiBaseLink: 'https://api.heriken.co',
  apiBaseLinkPackages:'https://api.softlabit.com',
  // apiBaseLinkPackages:'https://softlabit.com/package-booking/648088ece468c7183aed4b9b',
  ftpBaseLink: 'http://localhost:3000',
  appBaseUrl: '/',
  adminBaseUrl: 'admin',
  adminLoginUrl: 'admin/login',
  userBaseUrl: '',
  userProfileUrl: '/my-profile',
  userLoginUrl: 'login',
  storageSecret: 'SOFT_2021_IT_1998',
  adminTokenSecret: 'SOFT_ADMIN_1995_&&_SOJOL_dEv',
  userTokenSecret: 'SOFT_ADMIN_1996_&&_SOBUR_dEv',
  apiTokenSecret: 'SOFT_API_1998_&&_SAZIB_dEv',
  VERSION: 1
};
